In [1]:
import torch

# autograd

In [3]:
#autograd
x = torch.randn(3)
print(x)

tensor([-2.1203,  1.1066, -1.1944])


In [5]:
x = torch.randn(3, requires_grad = True)
print(x)

tensor([ 0.5826,  0.5648, -0.3017], requires_grad=True)


In [6]:
y = x + 2
print(y)

tensor([2.5826, 2.5648, 1.6983], grad_fn=<AddBackward0>)


In [7]:
z = y * y * 2
print(z)

tensor([13.3401, 13.1563,  5.7686], grad_fn=<MulBackward0>)


In [8]:
z = z.mean()#it will bring a scalar data
print(z)

tensor(10.7550, grad_fn=<MeanBackward0>)


In [9]:
z.backward()#dz/dx
print(x.grad)

tensor([3.4435, 3.4197, 2.2644])


In [12]:
x = torch.randn(3, requires_grad = True)
print(x)
y = x + 2
print(y)
z = y * y * 2
print(z)
v = torch.tensor([0.1,1.0,0.001],dtype = torch.float32)
z.backward(v)#dz/dx
print(x.grad)

tensor([-2.1234,  0.6826, -0.1462], requires_grad=True)
tensor([-0.1234,  2.6826,  1.8538], grad_fn=<AddBackward0>)
tensor([ 0.0305, 14.3923,  6.8735], grad_fn=<MulBackward0>)
tensor([-4.9380e-02,  1.0730e+01,  7.4154e-03])


## x.requires_grad_(False)
## x.detach()
## with torch.no_grad():

In [15]:
x = torch.randn(3, requires_grad = True)
print(x)


x.requires_grad_(False)
print(x)
y = x.detach()
print(y)
with torch.no_grad():
    y = x + 2
    print(y)

tensor([ 0.1806,  1.0684, -0.8888], requires_grad=True)
tensor([ 0.1806,  1.0684, -0.8888])
tensor([ 0.1806,  1.0684, -0.8888])
tensor([2.1806, 3.0684, 1.1112])


In [17]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(1):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])


In [18]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(2):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)#calculate the gradient model_output about weights

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])


In [19]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(2):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [31]:
weights = torch.ones(4, requires_grad=True)
print([weights])
optimizer = torch.optim.SGD([weights], lr=0.01)
optimizer.step()
print(optimizer.zero_grad())

[tensor([1., 1., 1., 1.], requires_grad=True)]
None
