In [2]:
import torch

In [3]:
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [4]:
x = torch.empty(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [5]:
x = torch.ones(2,2, dtype=torch.int)
print(x.size())
print(x)

torch.Size([2, 2])
tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


In [6]:
x = torch.tensor([2.5,0.1])
x

tensor([2.5000, 0.1000])

In [7]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.0101, 0.0967],
        [0.3789, 0.2633]])
tensor([[0.1110, 0.0996],
        [0.9145, 0.5456]])


In [8]:
z = torch.add(x,y)
z

tensor([[0.1210, 0.1963],
        [1.2934, 0.8090]])

In [9]:
y.add_(x)
print(y)

tensor([[0.1210, 0.1963],
        [1.2934, 0.8090]])


In [10]:
z = torch.sub(x,y)
z

tensor([[-0.1110, -0.0996],
        [-0.9145, -0.5456]])

In [11]:
z = torch.mul(x,y)
z

tensor([[0.0012, 0.0190],
        [0.4901, 0.2130]])

In [12]:
z = torch.div(x,y)
z

tensor([[0.0831, 0.4928],
        [0.2930, 0.3255]])

In [13]:
x = torch.rand(5,3)
print(x)
print(x[:, 0])
print(x[1, :])
print(x[1,1].item())

tensor([[0.4903, 0.5725, 0.0292],
        [0.5799, 0.4696, 0.4758],
        [0.4279, 0.1104, 0.4783],
        [0.4331, 0.6590, 0.3878],
        [0.8370, 0.2946, 0.9605]])
tensor([0.4903, 0.5799, 0.4279, 0.4331, 0.8370])
tensor([0.5799, 0.4696, 0.4758])
0.4696176052093506


In [14]:
x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)
y = x.view(-1,8)#automatically modify it
print(y)

tensor([[0.9724, 0.5139, 0.0533, 0.4783],
        [0.7520, 0.3538, 0.0827, 0.0940],
        [0.9479, 0.6664, 0.3853, 0.5739],
        [0.1082, 0.9338, 0.1008, 0.7280]])
tensor([0.9724, 0.5139, 0.0533, 0.4783, 0.7520, 0.3538, 0.0827, 0.0940, 0.9479,
        0.6664, 0.3853, 0.5739, 0.1082, 0.9338, 0.1008, 0.7280])
tensor([[0.9724, 0.5139, 0.0533, 0.4783, 0.7520, 0.3538, 0.0827, 0.0940],
        [0.9479, 0.6664, 0.3853, 0.5739, 0.1082, 0.9338, 0.1008, 0.7280]])


In [15]:
import numpy as np

In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
#if using the cup not gpu,change a will also change b,bacause they ude the same memory
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [18]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [19]:
print(b)

[2. 2. 2. 2. 2.]


In [20]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [21]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [22]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device = device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z = z.tp("cpu")

In [23]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
